
package com.epam.ticket.ejb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketServer", targetNamespace = "http://ejb.ticket.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketServer {


    /**
     * 
     * @param numberTicket
     * @return
     *     returns com.epam.ticket.ejb.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTicket", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.FindTicket")
    @ResponseWrapper(localName = "findTicketResponse", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.FindTicketResponse")
    Ticket findTicket(
        @WebParam(name = "numberTicket", targetNamespace = "")
        Integer numberTicket);

    /**
     * 
     * @param money
     * @param numberTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payTicket", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.PayTicket")
    @ResponseWrapper(localName = "payTicketResponse", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.PayTicketResponse")
    String payTicket(
        @WebParam(name = "numberTicket", targetNamespace = "")
        Integer numberTicket,
        @WebParam(name = "money", targetNamespace = "")
        Double money);

    /**
     * 
     * @param startCity
     * @param endDate
     * @param endCity
     * @param human
     * @param startDate
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookedTicket", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.BookedTicket")
    @ResponseWrapper(localName = "bookedTicketResponse", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.BookedTicketResponse")
    Integer bookedTicket(
        @WebParam(name = "startCity", targetNamespace = "")
        String startCity,
        @WebParam(name = "endCity", targetNamespace = "")
        String endCity,
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate,
        @WebParam(name = "human", targetNamespace = "http://ejb.ticket.epam.com/")
        Human human);

    /**
     * 
     * @param numberTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeTicket", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.RemoveTicket")
    @ResponseWrapper(localName = "removeTicketResponse", targetNamespace = "http://ejb.ticket.epam.com/", className = "com.epam.ticket.ejb.RemoveTicketResponse")
    String removeTicket(
        @WebParam(name = "numberTicket", targetNamespace = "")
        Integer numberTicket);

}
