
package com.epam.ticket.ejb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrainTicketJaxWsServersImplService", targetNamespace = "http://ejb.ticket.epam.com/", wsdlLocation = "http://localhost:45054/train-ticket-service-1.0/TicketServer?wsdl")
public class TrainTicketJaxWsServersImplService
    extends Service
{

    private final static URL TRAINTICKETJAXWSSERVERSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAINTICKETJAXWSSERVERSIMPLSERVICE_EXCEPTION;
    private final static QName TRAINTICKETJAXWSSERVERSIMPLSERVICE_QNAME = new QName("http://ejb.ticket.epam.com/", "TrainTicketJaxWsServersImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:45054/train-ticket-service-1.0/TicketServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRAINTICKETJAXWSSERVERSIMPLSERVICE_WSDL_LOCATION = url;
        TRAINTICKETJAXWSSERVERSIMPLSERVICE_EXCEPTION = e;
    }

    public TrainTicketJaxWsServersImplService() {
        super(__getWsdlLocation(), TRAINTICKETJAXWSSERVERSIMPLSERVICE_QNAME);
    }

    public TrainTicketJaxWsServersImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAINTICKETJAXWSSERVERSIMPLSERVICE_QNAME, features);
    }

    public TrainTicketJaxWsServersImplService(URL wsdlLocation) {
        super(wsdlLocation, TRAINTICKETJAXWSSERVERSIMPLSERVICE_QNAME);
    }

    public TrainTicketJaxWsServersImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAINTICKETJAXWSSERVERSIMPLSERVICE_QNAME, features);
    }

    public TrainTicketJaxWsServersImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrainTicketJaxWsServersImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketServer
     */
    @WebEndpoint(name = "TicketServerPort")
    public TicketServer getTicketServerPort() {
        return super.getPort(new QName("http://ejb.ticket.epam.com/", "TicketServerPort"), TicketServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketServer
     */
    @WebEndpoint(name = "TicketServerPort")
    public TicketServer getTicketServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb.ticket.epam.com/", "TicketServerPort"), TicketServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAINTICKETJAXWSSERVERSIMPLSERVICE_EXCEPTION!= null) {
            throw TRAINTICKETJAXWSSERVERSIMPLSERVICE_EXCEPTION;
        }
        return TRAINTICKETJAXWSSERVERSIMPLSERVICE_WSDL_LOCATION;
    }

}
